from pydantic import BaseModel, Field
from typing import List


class QuestionOutput(BaseModel):
    """
    Schema for the question generated by Gemini.
    Every question generated must match this exact structure.
    """
    question: str = Field(description="The interview question text")
    topic_tags: List[str] = Field(description="Topics this question covers e.g. ['attention', 'transformers']")
    key_concepts: List[str] = Field(description="Concepts a strong answer must include")
    difficulty: str = Field(description="Easy | Medium | Hard")