"""
Central configuration file.
All constants, settings, and environment-dependent values live here.
Never hardcode these values anywhere else in the project.
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ── API Settings ───────────────────────────────────────────
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
MODEL_NAME = "llama-3.3-70b-versatile"
MAX_RETRIES = 5
RETRY_WAIT_SECONDS = 30

# ── Interview Settings ─────────────────────────────────────
SUPPORTED_DOMAINS = [
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "LLMs",
    "DSA"
]

DIFFICULTY_LEVELS = ["Easy", "Medium", "Hard"]

DEFAULT_TOTAL_QUESTIONS = 5
QUESTION_OPTIONS = [3, 5, 7, 10]

# ── Scoring Thresholds ─────────────────────────────────────
SCORE_EXCELLENT  = 8.0   # green
SCORE_AVERAGE    = 5.0   # amber
# below 5.0      = red

# ── Adaptive Difficulty Thresholds ────────────────────────
INCREASE_DIFFICULTY_THRESHOLD = 8.0   # score >= this → harder
DECREASE_DIFFICULTY_THRESHOLD = 4.0   # score <= this → easier

# ── Calibration Thresholds ────────────────────────────────
CALIBRATION_TOLERANCE = 2.0   # gap within ±2 = well calibrated

# ── Confidence Mapping ─────────────────────────────────────
CONFIDENCE_OPTIONS = {
    "😰 Not Sure": 2.5,
    "😐 Somewhat Sure": 5.0,
    "😊 Confident": 7.5,
    "🚀 Very Confident": 10.0
}

# ── Database ───────────────────────────────────────────────
DB_PATH = os.path.join("data", "interview_judge.db")

# ── Logging ────────────────────────────────────────────────
LOG_DIR = "logs"
LOG_FILE = os.path.join(LOG_DIR, "app.log")
LOG_LEVEL = "INFO"

# ── PDF ────────────────────────────────────────────────────
PDF_FOOTER = "Generated by LLM Interview Judge • Powered by Groq + Streamlit"

# ── Recommendation Labels ──────────────────────────────────
RECOMMENDATIONS = ["Strong Hire", "Hire", "Maybe", "No Hire"]